TS  : 3B  Direct logic
TO  : 06  K    =     6 byte [historical characters]
A21310919000 ¢.....


0000  FF FF FF FF FF FF FF                             .......

Código SW: 9000

0000  A2 13 10 91 FF FF 81 15 FF FF FF FF FF FF FF FF  ................
0010  FF FF FF FF FF D2 76 00 00 04 00 FF FF FF FF FF  ......v.........
0020  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0030  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0040  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0050  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0060  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0070  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0080  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0090  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
00A0  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
00B0  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
00C0  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
00D0  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
00E0  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
00F0  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................

Código SW: 9000


